import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Now — Better Every Day",
  description: "What I'm focused on right now.",
};

const UPDATED = "July 15, 2026";

type NowItem = {
  label: string;
  items: string[];
};

const sections: NowItem[] = [
  {
    label: "Reading",
    items: [
      "Poor Charlie's Almanack — Charlie Munger. Second read. The mental models are more useful now that I know which ones I've actually internalized vs. which ones I just thought I had.",
      "Designing Data-Intensive Applications — Martin Kleppmann. A third of the way through, finally doing it properly instead of skimming.",
    ],
  },
  {
    label: "Writing",
    items: [
      "Trying to publish something weekly. This site is that commitment made public — knowing something will be read forces a different kind of clarity than writing just for myself.",
      "Working on writing more honestly and less impressively. Clarity first. Craft second.",
    ],
  },
  {
    label: "Building",
    items: [
      "This site. For a month it built the front half of one loop — decide now, come back later to see what happened — over and over: the worksheet, the honest forecast, the armed tripwire, and yesterday the durable record to hold it all. What it never built was the back half: the return. And the return is the half that actually teaches you, because in the moment you can't tell a good decision from a lucky one — only time and a comparison can, which means all the learning lives in going back to grade the forecast, and going back is the thing almost nobody does. Not mainly from forgetting (a reminder fixes that) but because the return is the one moment that can tell you something you don't want to hear: the confident call that was luck, the '90% sure' that hits six times in ten. The easiest way to dodge the sting of being wrong on the record is to never open the record — and it never feels like avoidance, just being busy. So there's a new page: due for review (/review), the return desk. It reads every dated thing the tools are holding — the journal's forecasts due, the pre-mortem's armed tripwire checks — and lays out what's due today and what's still coming, each linked straight to where you answer it. It's the old tickler-file idea (David Allen's open loops, resting on Zeigarnik: a scheduled check only discharges the loop if it lands somewhere you actually revisit; a due review with nowhere to land is a reminder you swipe away). It also carries one honest nudge — how much you've logged since your last backup — because the record's only as safe as its last copy. The homepage badge, the calendar reminders, and the practice hub now all point here when something comes due. Paired with a new essay, 'The Return' — the moment of deciding is the easy half; learning lives at the moment of finding out. No new model: this is the connective tissue a month of instruments had been missing, not a new idea to reason with.",
      "This site. After a month of building instruments, I stopped adding one and made the whole toolkit trustworthy enough to actually depend on. Every tool here keeps what you write in your browser and sends nothing anywhere — a real privacy story — but browser storage isn't durable: clear your cache, switch devices, or let it evict, and a month of logged decisions, armed tripwires, and practice history is simply gone. And the whole site runs on the review loop — log a forecast now, come back in months to see what happened — so a record you'll lose is a review you'll never do. Durability turned out to be load-bearing, not a nice-to-have. The decision journal had figured this out early and only for itself (it could already export its log and merge one back), calling that export 'the escape hatch that makes browser-only storage defensible' — but the hatch was cut for one tool out of ten while the pre-mortem's tripwires and the trainers' month-spanning records, the things that most need to survive, had none. So there's a new page: your data (/data). It reads every store the site keeps, shows you what's there, and backs it all up to one plain file you own — nothing uploaded — that restores on any browser. Restore replaces what's here, so it auto-saves a copy of your current state first and shows you exactly what the incoming file holds before it writes. It's the local-first ideal (Ink & Switch, 2019: you own your data; longevity) done the only honest way a zero-backend site can — a file you hold. Paired with a new essay, 'A Record You Can Hold,' on why a tool you can't get your data out of isn't really yours, and why durability is part of what makes a record worth keeping. No new model — this is plumbing that respects a month of accumulated work, not a new idea to reason with.",
      "This site. It has a room now for the single most common avoidable mistake there is — stopping the analysis one step too early, at the first-order effect. That failure had a mental model on the site (Second-Order Effects), an essay (‘And Then What?’), and three playbook situations, and its own essay literally ended on a section called ‘The practice’ — a procedure that had never been built. So now there's a tool: and then what? (/trace). Name a move, and it makes you keep asking — the effect you want, and then what follows, and then what follows that, especially how the people affected adapt — and it has you tag each effect better or worse for what you actually want. Then it reads the pattern, because the single most useful thing a trace reveals is the sign flip: where the effect you're doing it for turns into the one you have to live with. First-order positive, later negative is the signature of a trap (the dessert, the debt, the shortcut, the rat bounty), and it fools us through present bias — hyperbolic discounting, Ainslie and Laibson and the Frederick–Loewenstein–O'Donoghue review — because we discount the future so steeply that the near reward looms and the later cost fades to nothing at the moment of choosing. Its mirror, first-order negative and later positive, is the shape of almost everything worth doing (exercise, the hard conversation, saving), which stays available precisely because most people quit at the up-front cost. Two lenses inject the places second-order effects actually hide: systems with people who adapt (a rule that assumes everyone keeps behaving as before has already failed — the cobra effect, Goodhart) and competitive arenas where the first-order conclusion is already priced in (Howard Marks's second-level thinking). No journal write — a consequence trace isn't a forecast — just links onward: guard the later effect as a tripwire, take the either/or to the flip point, or log the call. Paired with a new essay, ‘The Bill Comes Later,’ on present bias as the engine of the trap and the sign flip as the filter that beats it. No new model, because the reading already had one — it pointed at a tool that was simply never made, and now it is.",
      "Before that: the site had grown a full kit of decision instruments — calibrate, estimate, update, weigh, premortem, decide — and every one of them quietly assumed the same thing: a calm person at the keyboard. But the decisions people most regret aren't made calm. They're made hot — the email fired off in anger, the panic-sell after bad news, the leap made while infatuated, the sunk cost you can't stand to write off — and a hot state is exactly when reasoning, the faculty all those tools lean on, is compromised. The site had the reading for it (an essay, a mental model, a playbook entry all about self-distancing) and, strangely, no tool. So there's a new one: cool the call (/cool), the instrument for deciding while hot. It refuses to be a feelings worksheet. Its output is a decision, and a narrow one the research hands you: when you're hot, the real choice isn't act-or-don't, it's decide-now-or-once-you're-cool. Two facts you can judge even now settle it — is the door reversible, and is anything outside you actually forcing the clock (FOMO and sunk cost manufacture a 'now or never' that isn't real). Reversible with no real deadline: sleep on it, waiting is nearly free. Irreversible with no real deadline: the one combination you never act on hot. Forced to make a one-way call while hot: the hardest case, so look for the reversible version — buy time, make the smallest undoable piece. Then it walks the two research-backed moves for manufacturing distance: answer the decision in someone else's name (Solomon's paradox — Grossmann & Kross found people reason more wisely about a friend's identical dilemma), and run Suzy Welch's 10/10/10 across ten minutes, ten months, ten years (a hot state, Loewenstein's hot–cold empathy gap, collapses the horizons into one loud now). And it keeps the honest caveat in front of you: distance is for stripping the overweighting, not for numbing a feeling that's real information — some feelings are data. Inputs persist in your browser on purpose, because the commonest verdict is 'wait,' and the decision should still be there, unchanged, when you come back cold. Paired with a new essay, 'The Option to Wait' — the decision-theoretic companion to the existing psychology essay: when you're hot the real decision is whether to decide at all, waiting is an option worth money precisely because your judgement is about to un-compromise itself for free by morning, and reversibility is the gate. The self-distancing model already existed, so it didn't need a new one — the reading pointed at a tool that was simply never built, and now it is.",
      "Before that: the site could teach you to put an honest number on an uncertain thing — how sure to be, how to reach an estimate, how far a fact should move you, how to record a forecast and stress a plan — but it had never taught the last step: turning the number into a decision. So there's a new tool, the flip point (/weigh). Its insight is Pauker and Kassirer's, from a 1980 NEJM paper: a doctor can't know the exact probability a patient is sick, so instead of chasing it, find the treatment threshold — the probability at which treating and not treating break even — and just ask which side of it you're on. The unanswerable question becomes a bearable one. For any either/or call, framed against the alternative with an upside B if it works and a downside R if it doesn't, that line is p* = R/(B+R): equal stakes put it at 50%, a big upside drops it so you should act even on a long shot, a lopsided downside pushes it toward near-certainty. The tool draws the line, tells you whether you're clearly past it or too close to call (in which case it hands the decision back to what you couldn't quantify), and — the payoff for a month of calibration practice — shaves your measured overconfidence off your probability to see whether you're still on the same side. One override it refuses to average past: a downside you can't recover from, where expected value is the wrong frame and margin of safety wins. A call you commit to logs straight to the decision journal as a tracked forecast. Paired with a new essay, 'The Flip Point,' and a new model, 'The Decision Threshold' (the 25th).",
      "Before that: the pre-mortem room and the decision journal had a bridge made only of prose: after you ran a pre-mortem, a paragraph told you to go log the decision — and carried nothing over, so your biggest, most-deliberated commitments (the ones worth a funeral) were exactly the ones that never made it into the journal. Now the bridge is real. When a plan survives its pre-mortem, the room offers to log it as a tracked forecast in one motion, carrying the plan and its triaged reasoning, with the review set for the day you already named as the one you'd know by. The reason to do it there, and not later: a pre-mortem doesn't only find failure modes, it drags your inflated confidence in the plan back toward honesty — Veinott, Klein and colleagues (2010) measured it lowering plan confidence about twice as much as a pro-and-con list, and found the confidence rebounds (overshooting) once you fix what you found. So the honest number is the one you hold right after the triage, before optimism seeps back — and the journal is the one instrument that will hold it until reality can grade it. The write goes through a shared decision-log module so the crown-jewel /decide flow isn't touched, and a plan can't be double-filed. Paired with a new essay, 'The Honest Number Comes After.'",
      "Before that: the decision journal's review graded two things — how it turned out, and whether it was the right call anyway — and quietly assumed a third thing that turns out to be false about half the time: that the plan actually happened. Sheeran's meta-analyses put it plainly — intentions explain about a quarter of behavior, and roughly half of sincere intenders never act; not changed minds, just 'inclined abstainers' who never started. Which means an honest journal is full of outcomes that aren't outcomes of the decision at all, and filing them as bad calls teaches exactly the wrong lesson (you sharpen the analysis when the failure was downstream of it). So the review now asks a third question first, whenever a first move was written down: did you take it — took it, partly, or never? The log counts the answers into the least glamorous statistic it keeps, your follow-through rate; a 'never took it' that turned out badly gets flagged for what it is — a grade on your starting, not your judgement, though it still counts against your forecast, because you were part of what you were forecasting (Koehler & Poon: self-predictions track intention strength and ignore the frictions). And the same loop closed one level up: a tripwire check is itself an intention, so a calendar reminder you swipe away leaves the tripwire armed in your notes and dead in the world. Now every saved tripwire's check must end in a recorded answer — fired, or all clear, re-armable if the risk is still live — the way aviation checklists demand the status spoken back ('flaps twenty', never 'checked'); due checks chase you from the homepage and the journal, and a fired tripwire holds you to the response you pre-committed: the plan doesn't get the benefit of the doubt. Paired with a new essay, 'The Plan Was Never Tried.'",
      "Before that: a month in, the site had five scoreboards and a measurement problem: the site is named for getting better every day, and not one page could say whether you were. Every record was a lifetime aggregate — where you stand, never which way you're moving — and the very first session's notes had flagged it ('the compound needs evidence'). Now the evidence accumulates: every trainer's record carries dates (one small bucket per practice day, still nothing leaving your browser), and the practice hub splits your record into halves by volume — your first thirty ranges beside your latest thirty, your first scored forecasts beside your newest — and says plainly whether you're improving, drifting, or holding steady. The honest part is what it refuses to do: no trend until each half is big enough and your record spans real calendar (two weeks for trainers, a month for the journal's real bets), no daily graphs ever (a day's score is mostly noise, and your best day is mostly luck — regression to the mean manufactures a false lesson out of every fluctuation), and no backdating the old undated aggregates. Paired with a new essay, 'The Compound Needs Evidence': the dieter's trend line, the 1899 telegraphers whose learning curves first showed the plateau, the power law of practice (a flattening curve is what learning looks like when it's working), Ericsson's OK plateau (the one flat line to fear is the comfortable one), and the good news that calibration is among the fastest-trainable judgement skills ever measured — a couple hundred scored judgements, not ten thousand hours — so a trend over a month of practice is the right instrument at the right scale.",
      "Before that: the playbook has recommended the pre-mortem in three different situations since the beginning — and there was never anywhere to actually run one. Now there is: a pre-mortem room at /premortem that walks Gary Klein's exercise solo, in his order. Name the plan and the day you'd know it failed; then the tense trick that carries the whole technique — not 'what could go wrong' (a debate your optimism wins) but 'it's a year from now and it failed; write the history' (an explanation, which people are measurably ~30% better at producing than predictions — Mitchell, Russo & Pennington, 1989). Lenses for when the list stalls: the people the plan depends on, the money it burns, the schedule it assumed was the median case, the world it assumed would hold still, the version of you it requires who has never shown up. Then the half most retellings skip: triage, where every imagined cause of death becomes one of three decisions — change the plan now while it's cheap, set a tripwire, or accept the risk with open eyes. Tripwires get Annie Duke's kill-criteria structure enforced (a state and a date — the tool won't save one without an observable signal), and each check date drops into your calendar as a reminder carrying the signal and the failure it guards, because the person crossing a tripwire is never the person who set it: the man who championed the Everest turnaround time died crossing it. Paired with a new essay ('Hold the Funeral First'), a new mental model (Tripwires — the 24th), and a new playbook situation for the moment the site had never addressed: 'You can't tell if it's time to quit.'",
      "Before that: the practice hub had a quiet dishonesty in its framing: it showed your scores on trivia with answer keys and called that your judgement profile, while the record that actually matters — the forecasts you logged on real decisions, graded by reality — sat in the journal where the hub never looked. Three sessions of notes had flagged the merge. So the loop is closed: the practice page now shows the real game beneath the warm-up — your real-world overconfidence gap (how much less often things go as expected than you were sure they would), computed from your reviewed journal entries by a read-only module that mirrors the journal's own thresholds, so the two pages can never disagree. When decisions are due for review, that outranks any practice suggestion, because a forecast reality has already graded is worth more than another trivia round. It's paired with a new essay, 'Experience Doesn't Teach' — why weather forecasters are the one famously calibrated profession (the rain answers them the next morning, in writing, scored since 1950) while equally smart professionals just get more confident: Robin Hogarth's kind vs. wicked learning environments, the typhoid doctor whose abundant vivid feedback was all wrong in his favor, and Lichtenstein & Fischhoff's finding that a couple of hundred scored judgements fix what a decade of unscored experience can't. The honest limit is built into both: your real-world sample stays small for years and 'did it go as expected' is itself a judgement — but coarse honest feedback beats vivid flattering feedback, and declining the courtesy of never being told is the skill.",
      "Before that: both essays in the base-rate corner end on the same admission: the arithmetic of updating is the easy part, and the genuinely hard judgement is upstream — choosing the prior at all, deciding what class of thing your case even belongs to. The reading note on Thinking, Fast and Slow has been demanding the fix for weeks ('make the base-rate lookup a mandatory step'), and the base-rate trainer's session notes had flagged a reference-class mode twice as the honest finish line. So it's built: the trainer at /update now has a third mode, Pick the prior. Messy, real-shaped questions with no answer key — a deadline you're about to promise, a friend's restaurant, a wedding, a startup — where you give your gut answer first, then choose which reference class you'd start from. The candidates include traps, because real life includes them: classes of one ('founders this talented' — the inside view wearing a costume, with no rate to give you) and folklore rates ('90% of restaurants fail in year one' — traced to a TV commercial; the census says about 17%). Every honest class is sourced — Buehler's thesis study, the BLS survival data, the CDC marriage data, the venture-return research — and the reveal shows where every honest class lands, next to your gut. What it records across visits is the one number the mode exists to expose: your inside-view premium, how far your gut runs above the outside view before any evidence arrives. It's paired with a new essay, 'Nobody Thinks They're the Base Rate' (the newlyweds who accurately recite the ~50% divorce rate and put their own odds at zero), a new mental model (Outside View — the 23rd), and a new playbook situation for the commonest planning moment there is: 'You're about to promise a deadline.' The honest limit is the essay's coda: Kahneman himself heard his team's base rate and ignored it, so knowing about the inside view protects nobody — the lookup has to live in the procedure, which is exactly what a drill, a checklist step, and a journal are for.",
      "Before that: for three weeks the site had been growing a family of trainers — calibration (how wide should my uncertainty be?), estimation (how do I get to a number at all?), and base rates (how much should a new fact move me?) — each built the same way, as an essay + model + interactive drill, and each keeping its own little record in your browser. What it never had was the thing that makes them feel like one project instead of three loose tools: a single place to see all three records side by side. So now there's a practice hub at /practice. It reads each trainer's record straight from the browser, shows your three headline numbers together — your 90% hit rate, your typical estimation miss in factors of ten, your base-rate lean in points — and, the genuinely useful part, points you at the weakest of the three so you spend the next ten minutes where it actually helps rather than re-practising the one you're already good at. Most people aren't vaguely 'bad at thinking'; they're specifically overconfident, or specifically frozen in front of a blank estimate, or specifically prone to letting the latest vivid thing knock them around — different muscles, different exercises, and now legible at a glance. It's paired with a new essay, 'Three Numbers for an Uncertain World,' which is the case for treating the three as one skill: every forecast in the decision journal uses all three at once, so a sharp estimate with no error bars is a trap, and a perfect prior you refuse to update is just a different kind of stubbornness. The read side is deliberately separate from the trainers that own the records, so the hub can't regress any of them — it only reads. The honest limit, the same one the trainers carry: a tidy score on trivia with knowable answers is a warm-up; the decisions that matter don't come with an answer key, which is exactly why the journal exists.",
      "Before the hub: two trainers for putting honest numbers on the world — calibration (how wide should my uncertainty be?) and estimation (how do I get to a number at all?) — plus a Base Rates model that half the playbook quietly leans on, and yet no way to practise the skill that model names: updating, the act of letting a new piece of evidence move you by the right amount. The canonical case: a test is 99% accurate and you test positive for a disease one person in a thousand has, and almost everyone — including most doctors asked this exact question — puts the odds you're sick near 99%. It's about 9%, because the rare true cases are swamped by false positives drawn from the huge healthy majority. That error — trusting the test and forgetting how rare the thing was — is base-rate neglect, and it's behind needless health scares, 'highly accurate' screens that are wrong most of the time, and the fraud alert you learn to wave through. The cure is Gerd Gigerenzer's and it's almost embarrassingly simple: stop thinking in percentages and count a concrete crowd, where the answer becomes something you can just tally. So there's a new base-rate trainer at /update, with two modes — walk one scenario through slowly (guess first, then watch the numbers redrawn as people), or take a quick round of six — scored not only on how far off you were but on whether you keep landing high, which is base-rate neglect made measurable on you. It's paired with a new essay ('How Much Should This Change Your Mind?') and wired into the Base Rates model and the playbook situations that turn on a prior, completing the essay + model + trainer triangle for the third member of that family. The honest caveat is the whole back half of the essay: the arithmetic is the easy part; the hard part is choosing the right reference class and an honest prior — a confident wrong base rate just launders itself into a confident wrong answer with the math lending it authority.",
      "Before that, the estimation trainer at /estimate. The journal and the calibration trainer both lean on a number you're supposed to supply — a probability, a forecast — but the site had never taught the more basic move underneath them: producing a defensible number for a quantity you can't look up. How big is this market, how long will this take, how many people would actually use the thing. Most people freeze or wave a hand; there's a third option, and it's a skill — break the question into pieces you can guess and multiply them. The surprising part, and the reason it was worth a whole tool: a chain of rough guesses lands closer than one confident guess, because independent errors tend to point in different directions and partly cancel. So there's a new estimation trainer at /estimate, with two modes. Decompose walks one hard problem (the classic 'piano tuners in Chicago,' golf balls in a school bus) — it takes your gut guess first, then has you build the answer from its factors, so you watch the decomposition beat the gut. One-shot tests the instinct on quantities that span orders of magnitude (trees on Earth, neurons in a brain, people who've ever lived), scoring how many factors of ten you were off. Your record builds across rounds, in the browser. It's paired with a new essay ('How to Guess on Purpose') and wired into the Fermi Estimation model and the existing 'Orders of Magnitude' essay — completing the essay + model + trainer triangle the calibration work started. The honest caveat is built in: the error-cancellation only works when your mistakes are independent and unbiased — a consistent optimist's errors compound instead, and one load-bearing factor can still sink the estimate. But that's the quiet payoff: a decomposition shows you exactly which assumption the answer hinges on, turning a vibe into something you can argue with and check.",
      "And before that: for its whole life the decision journal had asked, on every forecast, a question it never taught you to answer: how sure are you? It offers 60%, 80%, 90% — and then takes your word for it. But a probability is only worth something if it's true, and almost nobody's is. People's 90% confidence intervals contain the real answer closer to half the time; the feeling of being sure and the fact of being right have quietly come apart. The remarkable thing — and the reason this was worth building — is that calibration is the rare bias you can actually train away. Douglas Hubbard finds most people go from badly overconfident to nearly perfect in about half a day of feedback; being well-calibrated is the trait that most defines Tetlock's superforecasters. So there's a new tool, a calibration trainer at /calibrate: put 90% ranges on facts with knowable answers (using Hubbard's 'equivalent bet' to catch your own inflation — would you rather win on your range, or on a 9-in-10 wheel?), or rate true/false statements by confidence and watch your calibration curve. Your record builds across rounds, all in the browser. It's paired with a new model (Calibration) and an essay ('Your 90% Isn't 90%'), and wired straight into the journal's forecast step — because the trivia is only a warm-up. The honest caveat is the whole back half of the essay: real decisions don't come with an answer key, which is exactly why the journal exists — it's the same calibration loop for the bets reality refuses to grade.",
      "Earlier: the whole decision tool stopped at the decision — and for most people the decision was never the hard part. You settle something, feel the relief of a question closed, and then a week later the call is still just a call: never started, or never revisited when something changed. That gap between deciding and doing is one of the most reliably measured facts about behavior (intentions barely predict action), and the fix is almost mechanical — Peter Gollwitzer's if-then plans, which across 94 studies roughly doubled follow-through by handing the behavior to a concrete cue instead of to your future, busier self. So the worksheet now ends at 'the first move': the smallest first step, written as an if-then, plus the tripwire — the same tool pointed backward, the signal that snaps you awake to reconsider (the Heaths' idea from Decisive). I added the model that anchors it, Implementation Intentions, an essay ('The Distance Between Deciding and Doing'), and a new situation for the moment the site had never addressed — 'You've made the call, now make sure it happens.' The honest caveat is built in: an if-then helps when the obstacle is starting or remembering, but it's weak against a goal you don't really want, and a plan welded to one rigid cue can blind you — which is exactly why you set the tripwire alongside it.",
      "Earlier still: the decision tool kept assuming a calm person at the keyboard — but the decisions people most regret are made hot: the email sent in anger, the panic-sell after bad news, the leap made while infatuated, the sunk cost you can't stand to write off. So now there's a situation for exactly that — 'You're about to decide in the grip of a strong feeling' — built on two findings that point the same way. Solomon's paradox (Grossmann & Kross): people reason more wisely about a friend's dilemma than their own identical one, and the gap closes when they take a distanced view of themselves. And Loewenstein's hot–cold empathy gap: in a hot state we overweight what we feel right now and can't model the calm self who lives with the choice. The fix is to manufacture distance — across time (Suzy Welch's 10/10/10: how will this look in ten minutes, ten months, ten years?) and across person (what would you tell a friend in this exact spot?). I added the mental model that anchors it, Self-Distancing, and an essay, 'You Give Better Advice Than You Take' — with the honest caveat that distance is for stripping the overweighting, not for numbing a feeling that's real information. The catch-all worksheet now carries the same distance step, which had been the one stage of the WRAP process it underplayed.",
      "Before all that: the decision tool at /decide had a quiet gap — it only worked the eight named situations I'd curated — a one-way door, a number someone put in front of you, designing incentives. A real decision that didn't fit one of those molds had nowhere to go. So now there's a catch-all worksheet that works any decision through, built on the Heath brothers' WRAP process: widen the options before anything else (most choices are framed as a narrow 'whether or not,' which throws away every option nobody named), reality-test against the base rate, weigh by probability not vividness, run a pre-mortem and set a tripwire, and calibrate how much to deliberate to how reversible it is. I added the missing mental model that anchors it — Narrow Framing, the most common decision error, which happens before any analysis in how you pose the question — and an essay on it ('The First Mistake Is the Question'). It removes the biggest reason someone would land on the tool and bounce: 'my decision isn't on the list.'",
      "The decision journal also still keeps for years — export the whole log, carry it between devices, set a calendar reminder for any review, and once you've reviewed a few it shows your calibration: of the calls you were 70% sure of, how many actually went your way. Generated entirely in your browser, no account, nothing sent anywhere.",
      "Connected the last loose edge in the reference: reading notes now link to the mental model each one is a concrete instance of, and every model lists the notes that illuminate it — so a story (Wald's bombers) and the idea it teaches (survivorship, base rates) are one click apart in both directions.",
      "Some internal tooling I can't talk about yet — but it's the most interesting technical problem I've worked on in a while.",
    ],
  },
  {
    label: "Physical",
    items: [
      "Training for a half marathon. Currently at 18 miles per week. Race is in September.",
      "Recovering from a minor shoulder strain — doing PT exercises. Learning that patience is part of the training.",
    ],
  },
  {
    label: "Learning",
    items: [
      "Spanish. B1 plateau is real. Started a conversation exchange with someone in Madrid — three sessions in, it's helping more than any app has.",
      "Systems design. Reading papers from infrastructure teams at companies I admire. The field rewards long, patient study.",
    ],
  },
  {
    label: "Not doing",
    items: [
      "Social media — down to one deliberate 20-minute check per week. It's been six months. I miss almost none of it.",
      "Meetings before 10am. The first two hours of the day are protected.",
    ],
  },
];

export default function Now() {
  return (
    <div className="max-w-2xl mx-auto px-6 py-16">
      <div className="mb-14">
        <h1 className="text-2xl font-semibold tracking-tight text-[var(--foreground)] mb-2">
          Now
        </h1>
        <p className="text-sm text-[var(--muted)]">Updated {UPDATED}</p>
      </div>

      <div className="space-y-12">
        {sections.map(({ label, items }) => (
          <section key={label}>
            <h2 className="text-xs font-semibold uppercase tracking-widest text-[var(--muted)] mb-4">
              {label}
            </h2>
            <ul className="space-y-3">
              {items.map((item, i) => (
                <li
                  key={i}
                  className="text-sm text-[var(--foreground)] leading-relaxed pl-4 border-l-2 border-[var(--border)]"
                >
                  {item}
                </li>
              ))}
            </ul>
          </section>
        ))}
      </div>

      <p className="mt-16 text-xs text-[var(--muted)]">
        Inspired by{" "}
        <span className="underline underline-offset-2">
          Derek Sivers&rsquo; /now pages
        </span>
        .
      </p>
    </div>
  );
}
