import type { Metadata } from "next";
import Link from "next/link";
import { withSubject } from "../../data/carry";

export const metadata: Metadata = {
  title: "Deciding Hot, Worked Through — Better Every Day",
  description:
    "The other worked example. The flagship walkthrough follows a cold, deliberate decision agonized over for weeks. This one follows the decisions people actually regret — the ones made hot: the resignation typed in anger, pulse up, at 11pm. Watch one hot call go across the kit, where the toolkit's first move is to stop you from deciding at all — cool the call, park it, and let the return desk hand it back cold, then run the triage, log the real decision, and turn it into a first move. The exact words you typed in anger ride the through-line into every calm tool after it.",
  openGraph: {
    title: "Deciding Hot, Worked Through — Better Every Day",
    description:
      "One hot, clock-pressured call — 'quit my job today' — walked across the kit: cool the call and park it, come back cold to the reversibility triage, log the real decision, and turn it into a first move. The other spine of real deciding.",
    type: "website",
  },
};

/**
 * The hot spine, as a worked example — the peer to /example.
 *
 * /example walks the *cold, deliberate* spine: a job offer agonized over for
 * weeks, doors → weigh → premortem → decide → review. That's the calm person the
 * whole rest of the site assumes at the keyboard. But the decisions people most
 * regret aren't made calmly — they're made hot, and the kit has a whole branch
 * built for exactly that (cool → park → return cold → decide → act) that the cold
 * walkthrough can only gesture at. This page makes the emotional/urgent spine
 * legible the same way /example made the deliberate one: one real hot call,
 * walked across the tools in the open.
 *
 * Two things make it worth its own page rather than a second scenario bolted onto
 * /example. First, the *shape* is different: the toolkit's first and most
 * important move on a hot decision is to refuse to let you make it yet — cool the
 * call parks it and the return desk brings it back cold — which no cold example
 * can show. Second, and unlike the cold spine (which dead-ends at the
 * subject-less return desk), every tool on the hot spine reads the through-line,
 * so the exact words typed in anger ride into every calm tool after it; the page
 * carries the subject on all four steps and says so.
 *
 * Same discipline as /example: the step links are generated by the real
 * `withSubject` helper the live tools consume, so the page can't drift from the
 * behavior it demonstrates; the pre-fill can only ever add, never clobber; the
 * example decision is invented and nothing here is saved.
 */
const SUBJECT = "Quit my job today — I can't take another week of this.";

type Step = {
  n: number;
  /** The tool's full name, as it reads in its own header. */
  tool: string;
  /** Base href for the live tool. */
  href: string;
  /** Every tool on the hot spine reads the through-line — kept explicit so the
   *  page's own copy about "carried into every tool" can't quietly be wrong. */
  carries: boolean;
  /** The payoff badge, mirroring /tools and /example. */
  payoff: string;
  /** True on the first cold step — renders the "three days later" return beat. */
  coldReturnBefore?: boolean;
  /** The moment — what it feels like to be here, in the second person. */
  moment: string;
  /** What you'd actually put in front of the tool. */
  you: string;
  /** What the tool hands back. */
  back: string;
  /** The label on the link into the live tool. */
  cta: string;
};

const steps: Step[] = [
  {
    n: 1,
    tool: "Cool the Call",
    href: "/cool",
    carries: true,
    payoff: "Answers now",
    moment:
      "You're not weighing anything. Your pulse is up and it doesn't feel like a decision — it feels like the only sane response left. The resignation letter is half-written. This is the moment the rest of the kit can't reach, so it goes first.",
    you: "The call (“quit today”), what's driving it (anger, burnout), and the only two facts a hot head can still judge. Can you undo it? Quitting with nothing lined up is largely one-way — you can't un-quit this team, and a gap you'll have to explain doesn't un-write. Is anything outside you forcing the clock? No — there's no deadline tonight; the urgency is the feeling.",
    back: "One-way and not forced is the single combination you never act on hot: “Don't decide this tonight.” So you don't close the tab and hope you remember — you park it, scheduling it back in three days at the return desk, with a note to your cold self about what made it feel urgent. The heat can't win by default now. And parking isn't talking yourself out of it: if the call still stands cold, that's a reason to act, not proof you were overreacting.",
    cta: "Open cool the call, this decision loaded",
  },
  {
    n: 2,
    tool: "Which Door Is This?",
    href: "/doors",
    carries: true,
    payoff: "Answers now",
    coldReturnBefore: true,
    moment:
      "Three days on, the desk hands it back — cold, unchanged, the same words on the card. Now you can do the thing the heat wouldn't let you: sort what's actually reversible here from what isn't.",
    you: "The same decision, read with a steady pulse. Quitting this particular job is a one-way door — you can't un-resign. But “having a job at all” is a two-way door: you can job-hunt, you can leave later on better terms.",
    back: "It separates the irreversible edges from the reversible whole. So: give the parts that genuinely don't reverse — burning a reference, leaving mid-project, the résumé gap — the slow, careful thought they're owed, and stop letting them make the entire thing feel unfixable. The panic had fused a reversible situation to its one irreversible edge. Cold, they come apart.",
    cta: "Open the triage, this decision loaded",
  },
  {
    n: 3,
    tool: "The Decision Journal",
    href: "/decide",
    carries: true,
    payoff: "Sets up a return",
    moment:
      "Looked at squarely, the real decision isn't the one you typed at 11pm. It's not “quit today” — it's “leave within three months, on my terms, with something lined up.” That's a call worth making carefully, and worth remembering how you made it.",
    you: "The decision, the reasoning, and a forecast with a number on it: “I expect to be somewhere better — and glad I didn't slam the door — six months from now. Confidence: 70%.” Review date: six months out.",
    back: "It records the reasoning and seals the forecast, then schedules the one thing that teaches — a date to set what happened against what you expected. That 70% is now a bet reality will settle, not a story the memory of a bad night can rewrite. The call that started as a hot “get me out” is now a cold, dated plan.",
    cta: "Open the journal, this decision loaded",
  },
  {
    n: 4,
    tool: "Decided Isn't Done",
    href: "/act",
    carries: true,
    payoff: "Sets up a return",
    moment:
      "A decision to leave in three months is exactly the kind that quietly stays a decision — nothing moves, the months pass, and you're back at 11pm typing the same letter. So before you close the loop, turn the call into a first move.",
    you: "It first checks the honest thing most planning skips — is the hard part the doing, or do you not actually want this? — then the plan: the smallest first move bound to a cue (“when I sit down Sunday morning with coffee, I'll spend 30 minutes on my résumé”), a backup for the obstacle (“if I'm too drained, I message one former colleague instead”), and a tripwire that says stop and rethink.",
    back: "Three if-then sentences you can hold: one to start, one for when it stalls, one to reconsider. The tripwire is the honest bookend to the whole walk — if a specific line gets crossed at work, or nothing's moved by a date, that fires a return, armed now while you're calm. The decision that began as “quit tonight” is now a plan that starts on Sunday and knows exactly what would make you move faster.",
    cta: "Open make-it-happen, this decision loaded",
  },
];

const payoffStyle: Record<string, string> = {
  "Answers now": "text-[var(--accent)] border-[var(--accent)]",
  "Sets up a return": "text-[var(--muted)] border-[var(--muted)]",
  "A practice": "text-[var(--muted)] border-[var(--border)]",
};

export default function HotExamplePage() {
  return (
    <div className="max-w-2xl mx-auto px-6 py-16">
      <header className="mb-12">
        <p className="text-xs font-semibold uppercase tracking-widest text-[var(--muted)] mb-3">
          The other worked example
        </p>
        <h1 className="text-2xl font-semibold tracking-tight text-[var(--foreground)] mb-4">
          Deciding hot, worked through
        </h1>
        <p className="text-base text-[var(--muted)] leading-relaxed">
          The{" "}
          <Link
            href="/example"
            className="text-[var(--accent)] hover:opacity-70 transition-opacity"
          >
            flagship walkthrough
          </Link>{" "}
          follows a cold, deliberate call &mdash; a job offer agonized over for
          weeks. This is its opposite, and the one people actually regret: a
          decision made <em>hot</em>. Pulse up, a resignation half-typed at 11pm,
          feeling less like a choice than the only response left. Here&rsquo;s one
          such call &mdash; <em>quit my job today</em> &mdash; walked across the
          kit. Watch the one thing the cold walkthrough can&rsquo;t show you:{" "}
          <em>the toolkit&rsquo;s first move is to stop you from deciding at all.</em>
        </p>
        <p className="mt-4 text-base text-[var(--muted)] leading-relaxed">
          Every step links into the live instrument with this decision already
          loaded. And unlike the cold spine, <em>every</em> tool here reads the
          through-line &mdash; so the exact words you typed in anger ride into each
          calm tool after them, and three days later you don&rsquo;t have to
          reconstruct what you meant.
        </p>
      </header>

      {/* The subject that rides the through-line, shown once so the reader can see
          the exact text every step below carries — typed hot, then carried cold. */}
      <div className="mb-14 rounded-xl border border-[var(--border)] bg-[var(--card)]/60 p-5">
        <p className="text-xs font-semibold uppercase tracking-widest text-[var(--muted)] mb-2">
          The decision, typed once &mdash; hot
        </p>
        <p className="text-base font-medium text-[var(--foreground)] leading-relaxed pl-4 border-l-2 border-[var(--accent)]">
          {SUBJECT}
        </p>
        <p className="mt-3 text-sm text-[var(--muted)] leading-relaxed">
          You type this once, at the first tool, while your pulse is up. From
          there it&rsquo;s carried &mdash; into the triage, the journal, the
          first-move plan &mdash; never retyped, so the calm version of you a few
          days later picks up the exact words, not a softened memory of them.
        </p>
      </div>

      <ol className="space-y-14">
        {steps.map((step) => {
          const href = step.carries ? withSubject(step.href, SUBJECT) : step.href;
          return (
            <li key={step.n} className="relative">
              {step.coldReturnBefore ? (
                <div className="mb-12 rounded-xl border border-dashed border-[var(--accent)] bg-[var(--card)]/40 p-5">
                  <p className="text-xs font-semibold uppercase tracking-widest text-[var(--accent)] mb-2">
                    Three days later &mdash; the return desk hands it back, cold
                  </p>
                  <p className="text-sm text-[var(--muted)] leading-relaxed">
                    You don&rsquo;t have to remember to come back. On the day you
                    set, the{" "}
                    <Link
                      href="/review"
                      className="text-[var(--accent)] hover:opacity-70 transition-opacity"
                    >
                      return desk
                    </Link>{" "}
                    surfaces the parked call and reopens it cold. This is the beat
                    the deliberate walkthrough has no room for: the most important
                    move on a hot decision was <em>not made yet</em> &mdash; and
                    now, calm, you make it.
                  </p>
                </div>
              ) : null}

              <div className="flex items-baseline justify-between gap-4 mb-3">
                <div className="flex items-baseline gap-3">
                  <span className="text-sm font-mono text-[var(--muted)] tabular-nums">
                    {String(step.n).padStart(2, "0")}
                  </span>
                  <h2 className="text-xl font-semibold tracking-tight text-[var(--foreground)] leading-snug">
                    {step.tool}
                  </h2>
                </div>
                <span
                  className={`shrink-0 text-[10px] font-semibold uppercase tracking-widest px-1.5 py-0.5 rounded border ${payoffStyle[step.payoff]}`}
                >
                  {step.payoff}
                </span>
              </div>

              <p className="text-sm font-medium text-[var(--foreground)] leading-relaxed mb-4">
                {step.moment}
              </p>

              <div className="space-y-4 text-sm leading-relaxed">
                <div>
                  <span className="text-xs font-semibold uppercase tracking-widest text-[var(--muted)]">
                    What you put in
                  </span>
                  <p className="mt-1.5 text-[var(--muted)] leading-relaxed">
                    {step.you}
                  </p>
                </div>
                <div>
                  <span className="text-xs font-semibold uppercase tracking-widest text-[var(--muted)]">
                    What it hands back
                  </span>
                  <p className="mt-1.5 text-[var(--foreground)] leading-relaxed pl-4 border-l-2 border-[var(--accent)]">
                    {step.back}
                  </p>
                </div>
              </div>

              <Link
                href={href}
                className="inline-block mt-4 text-sm font-medium text-[var(--accent)] hover:opacity-70 transition-opacity"
              >
                {step.cta} &rarr;
              </Link>
            </li>
          );
        })}
      </ol>

      <div className="mt-16 pt-8 border-t border-[var(--border)]">
        <h2 className="text-base font-semibold text-[var(--foreground)] mb-3">
          What just happened
        </h2>
        <p className="text-sm text-[var(--muted)] leading-relaxed">
          A decision that started as <em>&ldquo;quit tonight&rdquo;</em> ended as a
          dated plan that starts on Sunday. The kit&rsquo;s first move wasn&rsquo;t
          to help you decide &mdash; it was to <em>stop</em> you deciding while hot,
          park the call, and hand it back once you could see it straight. Only then
          did the triage, the journal, and the first-move plan do their work. That
          order is the whole point: on a hot decision, the sequence matters more
          than any single tool.
        </p>
        <p className="mt-4 text-sm text-[var(--muted)] leading-relaxed">
          And you typed the decision <em>once</em> &mdash; hot, at 11pm. The
          through-line carried those exact words into every calm tool after it, so
          three days later the cold version of you didn&rsquo;t start from a blank
          field and a softened memory. That&rsquo;s the toolkit working as{" "}
          <em>one instrument</em> across a gap of days, not four forms you&rsquo;d
          have had to fill from scratch once the heat had faded and the details with
          it.
        </p>
        <div className="mt-8 flex flex-wrap gap-x-6 gap-y-2">
          <Link
            href={withSubject("/cool", SUBJECT)}
            className="text-sm font-medium text-[var(--accent)] hover:opacity-70 transition-opacity"
          >
            Walk your own hot call through, starting at cool &rarr;
          </Link>
          <Link
            href="/example"
            className="text-sm font-medium text-[var(--accent)] hover:opacity-70 transition-opacity"
          >
            Or see the cold, deliberate spine &rarr;
          </Link>
          <Link
            href="/tools"
            className="text-sm font-medium text-[var(--accent)] hover:opacity-70 transition-opacity"
          >
            Or pick the tool for the moment you&rsquo;re in &rarr;
          </Link>
        </div>
        <p className="mt-8 text-xs text-[var(--muted)] leading-relaxed">
          Nothing on this page is saved, and the example decision is invented. When
          you open a tool with a decision loaded, it fills the field only if you
          haven&rsquo;t already got work there &mdash; the example can never write
          over something of yours. Everything you enter in the tools stays in your
          browser and is sent nowhere.
        </p>
      </div>
    </div>
  );
}
